# Generated by Django 5.0.7 on 2024-07-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password1',
            field=models.CharField(max_length=250),
        ),
    ]
